#!/bin/bash
# Digger by Tpayne | github.com/realtpayne/digger

#This script was originally created to quickly verify the DNS of domains reported for abuse, as these reports would come in many formats I wanted something that could retrieve the domain from whatever was provided even when extra data (https / the URI) or erroneous spaces were included.

#colors
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[1;32m'


mainstart(){
	if [ "$#" -eq 0 ] ; then
		usage ;
	else
		for var in "$@" ;
		do if [[ ${var} == -h || ${var} == --help ]] ; then
			usage ;
		elif [[ ${var} == -s ||  ${var} == --subdomain ]] ; then
			subdomainflag=1 ;
		elif [[ ${var} == -l || ${var} == --sslcheck ]] ; then
			if type nc > /dev/null 2>&1 ; then
				sslcheckflag=1
			else
				sslcheckskipped=1
			fi

		elif [[ ${var} == "-d" || ${var} == "--dmarclookup" ]] ; then
			verbosedmarclookup=1
		else
			filteredlist+=($var) ;
		fi
		done
	fi	
}

usage(){
>&2 cat << EOF
Usage: $0 [OPTIONS] <domain>
Accepted input formats to demonstate the pattern matching available in the tool:
$0 -h https://domain.tld/uri
$0 domain.tld
$0 https : / / domain.tld/uri --help
Available options:
	[ -h | --help] | This output here
	[ -s | --subdomain ] | Pull the SOA from the DNS lookup and compares the subdomains DNS at the authortative zone
	[ -l | --sslcheck ] | Validate if port 80 and 53 is open and accepting requests, requires nc be installed
EOF
exit 1
}

noservers(){
	echo -e "\nThe nameserver $1 responded with ${RED}no servers could be reached${NC} when asked about $2"
	echo -e "\nThis can be verified by you by running the dig below\n${RED}\tdig @$1 $2 a +short${NC}"
}

portcheck(){
for ip in "$@" ; 
do 
	nc -w 5 -vz ${ip} 80 >/dev/null 2>&1 && echo -e "${GREEN}TCP port 80 is open on ${ip}${NC}" || echo -e "${RED}unable to detect TCP Port 80 is open on ${ip}${NC}";
	nc -w 5 -vz ${ip} 53 >/dev/null 2>&1 && echo -e "${GREEN}TCP port 53 is open on ${ip}${NC}" || echo -e "${RED}unable to detect TCP Port 53 is open on ${ip}${NC}";
	nc -w 5 -vz -u ${ip} 53 >/dev/null 2>&1 && echo -e "${GREEN}UDP port 53 is open on ${ip}${NC}" || echo -e "${RED}unable to detect UDP Port 53 is open on ${ip}${NC}";
done
}


lookup(){
	    var="$@"; # sets var as everything passed from mainstart
	    var="$(echo ${var} | tr ':UPPER:' ':LOWER:')"; # lower cases the above variable
	    var=${var// /} # removes spaces from the above
	    var1=$(echo ${var}|sed -e 's|^[^/]*//||' -e 's|/.*$||'); # if provided in https://domain.tld/path/to/uri , formats out only the domain.tld
	    var2=$(echo -e ${var1} | cut -d. -f2-) # the previous domain level, needed for subdomain lookup
	    printf '%s\n\n' "DNS for Domain ${var1}";
	    if [[ -n $(dig DS ${var1} +short) ]]; then
		    echo -e "DNSSEC enabled\n";
		    resolver="";
	    else
		    resolver="@208.67.222.222";
	    fi;
	    for type in SOA NS A AAAA MX TXT;
	    do
		    echo " --${type}:";
		    if [[ ${type} =~ NS && ${#subdomainflag[@]} -eq 1 ]]; then
			echo -e "${GREEN}Subdomain specified, using parent domain '${var2}' nameservers${NC}";
			dig ${resolver} +short ${type} $(echo ${var1} | cut -d. -f2-);
			echo;
			for mx in $(dig ${resolver} +short ${type} $(echo ${var1} | cut -d. -f2-)| awk '{sub(/\.$/,"",$0);print $NF}'); 
			do
				echo -n "${mx}: ";
				dig ${resolver} +short ${mx}
			done;
			else  
			dig ${resolver} +short ${type} ${var1};
			if [[ ${type} =~ MX|NS ]]; then
			    echo;
			    for mx in $(dig ${resolver} +short ${type} ${var1}|awk '{sub(/\.$/,"",$0);print $NF}');
			    do
				    echo -n "${mx}: ";
				    dig ${resolver} +short ${mx};
			    done;
		    fi;
		    echo;
		    fi;
	    done;
		    
	    echo -e "Checking service subdomain routing\n" ;
	    for subdomain in www mail cpanel webmail webdisk cpcontacts cpcalendars whm;
	    do
		    echo -e "-- ${subdomain}.${var1}" ;
		    dig ${resolver} a ${subdomain}.${var1} +short ;
	    done;
	    unset resolver;
	    echo -e "\nChecking Dmarc record now\n"
	    dmarclookup ${var1}
	    
	    echo -e "\nChecking if nameservers report A records for ${var1}\n";

	    if [[ ${#subdomainflag[@]} -eq 1 ]]; then
		    echo
		    echo -e "${GREEN}Subdomain specified, using parent domain '${var2}' nameservers${NC}";
		    echo
		    nameservers=($(dig ${var2} ns +short));
	    else
		    nameservers=($(dig ${var1} ns +short));
	    fi 
		    for ns in ${nameservers[@]};
		    do
			    response=($(dig @${ns} ${var1} a +short))
			    if [ ${#response[@]} -eq 0 ] ; then
				    echo -e "${RED}${ns} responded with no record for ${var1}${NC}"
			   elif [[ "${response[*]}" =~ "no servers could be reached" ]] ; then
				   noservers ${ns} ${var1}
			   elif [[ -n $(dig @${ns} ${var1} cname +short) ]]; then
				   echo -e "${ns} returned the cname record ${response[*]} for ${var1} performing second lookup";
				   dig $(dig @${ns} ${var1} cname +short) a +short;
			   else 
				   echo -e "${ns} returned the following record(s) for ${var1} : ${response[*]}";  
				   unset response
			    fi
		    done

		if [[ ${#sslcheckflag[@]} -eq 1 ]] ; then
			echo -e "\nPortchecking starts now, if the script hangs here theres likely a network problem\n"
		fi

		if [[ ${#sslcheckflag[@]} -eq 1 && ${#subdomainflag[@]} -eq 1 && ${#sslcheckskipped[@]} -ne 1 ]] ; then
			portcheck $(dig ${var2} +short)
		elif [[ ${#sslcheckflag[@]} -eq 1 && ${#sslcheckskipped[@]} -ne 1 ]] ; then
			portcheck $(dig ${var1} +short)
		elif [[ ${#sslcheckskipped[@]} -eq 1 ]] ; then
			echo -e "${RED}executable for NC not found, so the SSL check is skipped${NC}"
		fi	
		
		unset mx type
}

dmarclookup(){
IFS=';' # I need this to help parse dmarc with minimal logic
dmarc_output=$(dig txt _dmarc.$1 +short)
for rule in ${dmarc_output[@]}
do list+=$(echo ${rule} | tr -d '"' )
done
unset IFS # I no longer need it and now it causes issues
for tag in ${list[@]}
do
	if [[ ${tag} =~ "p=" && ! ${tag} =~ "sp=" ]] ; then
		dmarcpolicy=1 && verbosep=${tag}	;
	elif [[ ${tag} =~ 'v=' ]] ; then
	        dmarcversion=1 && verboseversion=${tag}
       elif [[ ${tag} =~ "sp=" ]] ; then
	       dmarcsubpolicy=1 && verbosesubpolicy=${tag};
       elif [[ ${tag} =~ "rf=" ]] ; then
	       forensicreport=1 && verboseforensic=${tag};
       elif [[ ${tag} =~ "pct=" ]] ; then
	       percentagepolicy=1 && verbosepercentage=${tag}  ;
       elif [[ ${tag} =~ "ri=" ]] ; then
	       reportinginterval=1 && verbosereporting=${tag} ;
       elif [[ ${tag} =~ "fo=" ]] ; then
	       failureoption=1 && verbosefailure=${tag};
       elif [[ ${tag} =~ "rua=" ]] ; then
	       ruaset=1 && verboserua=${tag};
       elif [[ ${tag} =~ "ruf=" ]] ; then
	       rufset=1 && verboseruf=${tag};
       elif [[ ${tag} =~ "adkim=" ]] ; then
	       verboseADKIM=${tag};
       elif [[ ${tag} =~ "aspf=" ]] ; then
	       verboseASPF=${tag};
	fi
done

if [[ ${#dmarcversion[@]} -eq "1" && ${#dmarcpolicy[@]} -eq "1" && ${#verbosedmarclookup[@]} -ne 1 ]] ; then
	echo "Dmarc for domain is syntactically valid. Full record below" ;
	echo -e "${dmarc_output[*]}";
elif [[ ${#verbosedmarclookup[@]} -eq "1" ]] ; then
	if [[ ${#dmarcversion[@]} -eq "1" && ${#dmarcpolicy[@]} -eq "1" ]] ; then
		echo "Dmarc is valid, I found a policy and a version. Full record below"
		echo -e "Dmarc -- ${dmarc_output[*]}";	
		echo "Dmarc verbose lookup was passed so I will explain what I found below";
		echo "Dmarc Policy: ${verbosep}"
		echo -e "\tOptions available are 'None', 'Quarantine', 'Reject'."
		echo "Dmarc Version: ${verboseversion}"
	elif [[ ${#dmarcversion[@]} -ne "1" || ${#dmarcpolicy[@]} -ne "1" ]] ; then
		if [[ ${#dmarcversion[@]} -ne "1" ]] ; then
			echo "Dmarc Version tag not present, this is a required option."
		fi
		if [[ ${#dmarcpolicy[@]} -ne "1" ]] ; then
			echo "Dmarc Policy tag not present, this is a required option."
		fi
	fi
	if [[ ${#verbosesubpolicy[@]} -eq "1" ]] ; then
		echo "Dmarc Subdomain Policy: ${verbosesubpolicy}" ;
		echo -e "\tThis optional policy instructs specific policy handling for subdomains." 
	fi
	if [[ ${#verboseforensic[@]} -eq "1" ]] ; then
		echo "Dmarc Report Format: ${verboseforensic}";
		echo -e "\tThis is an optional dmarc policy which sets the format of Foresic reports.";
		echo -e '\tThis AFRF format (Authentication Failure Reporting Format) is the only supported option for this.';
	fi
	if [[ ${#verbosepercentage[@]} -eq "1" ]] ; then
		echo "Dmarc Percentage Policy: ${verbosepercentage}" ;
		echo -e "\tThis optional policy specifies the percentage of email messages subjected to Dmarc filtering." 
		echo -e "\tFor example, pct=25 means that a quarter of the emails will be filtered by the recipient."
	fi
	if [[ ${#verbosereporting[@]} -eq "1" ]] ; then
		echo "Dmarc Report Interval: ${verbosereporting}";
		echo -e "\tThis optional policy will instruct the interval in seconds between when Aggregate reports can be sent."
	fi
	if [[ ${#verboseADKIM} -eq "1"  ]] ; then
		echo "Dmarc Alignment for DKIM set: ${verboseADKIM}"
		echo -e "\tThis accepts Relaxed and strict alignements, -r for relaxed | -s for strict"
		echo -e "\tPass / Fail Scenarios in Strict DKIM Alignment"
		echo -e "\tDKIM Domain is mail.example.com, Header From Domain is mail.example.com, Result is passed"
		echo -e "\tDKIM Domain is mail.example.com, Header From Domain is example.com, Result is failed\n"
		echo -e "\tPass / Fail Scenarios in Relaxed Alignment"
		echo -e "\tDKIM Domain is mail.example.com, Header From Domain is example.com, Result is Pass"
		echo -e "\tDKIM Domain is example.mail.com, Header From Domain is example.com, Result is Failed"
	fi
	if [[ ${#verboseASPF[@]} -eq "1" ]] ; then 
		echo "Dmarc alignment for SPf set: ${verboseASPF}"
		echo -e "\tThis accepts Relaxed and strict alignements. -r for relaxed | -s for strict"
		echo -e "\tPass / Fail Scenarios in Strict SPF Alignment"
		echo -e "\tMailFROM Domain is mail.example.com, Header From Domain is mail.example.com, Result is Pass"
		echo -e "\tMailFROM Domain is mail.example.com, Header From Domain is example.com, Result is Fail"
		echo -e "\tPass / Fail Scenarios in Relaxed SPF Alignment"
		echo -e "\tMailFROM Domain is mail.example.com, Header From Domain is example.com, Result is Pass"
		echo -e "\tMailFROM Domain is example.mail.com, Header From Domain is example.com, Result is Fail"

	fi 
	if [[ ${#verbosefailure[@]} -eq "1" ]] ; then
		echo "Dmarc Failure Reporting: ${verbosefailure}";
		echo -e "\tThis optional policy sets the failure reporting options, the following options are available."
		echo -e "\tfo=0 - only generates a report if both SPF and DKIM fail to validate."
		echo -e "\tfo=1 - will generate a report if SPF or DKIM fail to validate."
		echo -e "\tfo=s - Generates an SPF failure report if SPF checks fail, regardless of alignment in aspf policy."
		echo -e "\tfo=d - Generates an DKIM failure report if DKIM fails, regardless of alignment in adkim policy."
		echo -e "\tfo=0:s:d is an example of multiple types of reports, this example indicates the rulesets from 0, s, and d are all enforced."
	fi
	if [[ ${#ruaset[@]} -eq "1" ]] ; then
		echo "Dmarc RUA Policy: ${verboserua}"
		echo -e "\tThis will be the address that aggregate feedback reports are sent to."
	fi
	if [[ ${#rufset[@]} -eq "1" ]] ; then
		echo "Dmarc RUF Policy: ${verboseruf}"
		echo -e "\tThis will be the address that Forensic reports are sent to.";
	fi

fi
}

mainstart $@
if [ ${#filteredlist[@]} -gt 0 ] ; then
	lookup ${filteredlist[@]} ;
fi
